ifeq ($(CONFIG_PROJECT_GARLIC),y)
dtb-$(CONFIG_ARCH_MSM8937) += msm8937-pmi8950-mtp-garlic.dtb
else
dtb-$(CONFIG_ARCH_MSM8996) += msm8996-v2-pmi8994-mtp.dtb \
	msm8996-v2-pmi8994-pmk8001-mtp.dtb \
	msm8996-v2-pmi8994-pm8004-mtp.dtb \
	msm8996-v2-pmi8994-pm8004-pmk8001-mtp.dtb \
	msm8996-v2-fluid.dtb \
	msm8996-v2-liquid.dtb \
	msm8996-v2-dtp.dtb \
	msm8996-v3-auto-cdp.dtb \
	msm8996-v3-auto-adp.dtb \
	msm8996-v3-pmi8994-cdp.dtb \
	msm8996-v3-pmi8994-mtp.dtb \
	msm8996-v3-pmi8994-pmk8001-cdp.dtb \
	msm8996-v3-pmi8994-pmk8001-mtp.dtb \
	msm8996-v3-pmi8994-pm8004-cdp.dtb \
	msm8996-v3-pmi8994-pm8004-mtp.dtb \
	msm8996-v3-pmi8994-pm8004-pmk8001-cdp.dtb \
	msm8996-v3-pmi8994-pm8004-pmk8001-mtp.dtb \
	msm8996-v3-pmi8996-cdp.dtb \
	msm8996-v3-pmi8996-mtp.dtb \
	msm8996-v3-pmi8996-pmk8001-cdp.dtb \
	msm8996-v3-pmi8996-pmk8001-mtp.dtb \
	msm8996-v3-fluid.dtb \
	msm8996-v3-liquid.dtb \
	msm8996-v3-dtp.dtb \
	msm8996-v3-pm8004-mmxf-adp.dtb \
	msm8996-v3-pm8004-agave-adp.dtb \
	msm8996-v3-pm8004-agave-adp-lite.dtb \
	msm8996pro-auto-adp.dtb \
	msm8996pro-auto-adp-lite.dtb \
	msm8996pro-auto-cdp.dtb \
	msm8996pro-pmi8994-cdp.dtb \
	msm8996pro-pmi8994-mtp.dtb \
	msm8996pro-pmi8994-pmk8001-cdp.dtb \
	msm8996pro-pmi8994-pmk8001-mtp.dtb \
	msm8996pro-pmi8994-pm8004-cdp.dtb \
	msm8996pro-pmi8994-pm8004-mtp.dtb \
	msm8996pro-pmi8994-pm8004-pmk8001-cdp.dtb \
	msm8996pro-pmi8994-pm8004-pmk8001-mtp.dtb \
	msm8996pro-pmi8996-cdp.dtb \
	msm8996pro-pmi8996-mtp.dtb \
	msm8996pro-pmi8996-pmk8001-cdp.dtb \
	msm8996pro-pmi8996-pmk8001-mtp.dtb \
	msm8996pro-v1.1-auto-cdp.dtb \
	msm8996pro-v1.1-pmi8994-cdp.dtb \
	msm8996pro-v1.1-pmi8994-mtp.dtb \
	msm8996pro-v1.1-pmi8994-pmk8001-cdp.dtb \
	msm8996pro-v1.1-pmi8994-pmk8001-mtp.dtb \
	msm8996pro-v1.1-pmi8994-pm8004-cdp.dtb \
	msm8996pro-v1.1-pmi8994-pm8004-mtp.dtb \
	msm8996pro-v1.1-pmi8994-pm8004-pmk8001-cdp.dtb \
	msm8996pro-v1.1-pmi8994-pm8004-pmk8001-mtp.dtb \
	msm8996pro-v1.1-pmi8996-cdp.dtb \
	msm8996pro-v1.1-pmi8996-mtp.dtb \
	msm8996pro-v1.1-pmi8996-pmk8001-cdp.dtb \
	msm8996pro-v1.1-pmi8996-pmk8001-mtp.dtb \
	apq8096pro-auto-cdp.dtb \
	apq8096pro-v1.1-auto-adp.dtb \
	apq8096pro-v1.1-auto-adp-lite.dtb \
	apq8096pro-liquid.dtb \
	apq8096pro-v1.1-auto-cdp.dtb \
	apq8096pro-v1.1-pmi8994-cdp.dtb \
	apq8096pro-v1.1-pmi8994-mtp.dtb \
	apq8096pro-v1.1-pmi8994-pmk8001-cdp.dtb \
	apq8096pro-v1.1-pmi8994-pmk8001-mtp.dtb \
	apq8096pro-v1.1-pmi8994-pm8004-cdp.dtb \
	apq8096pro-v1.1-pmi8994-pm8004-mtp.dtb \
	apq8096pro-v1.1-pmi8994-pm8004-pmk8001-cdp.dtb \
	apq8096pro-v1.1-pmi8994-pm8004-pmk8001-mtp.dtb \
	apq8096pro-v1.1-pmi8996-cdp.dtb \
	apq8096pro-v1.1-pmi8996-mtp.dtb \
	apq8096pro-v1.1-pmi8996-pmk8001-cdp.dtb \
	apq8096pro-v1.1-pmi8996-pmk8001-mtp.dtb \
	msm8996-v3.0-pmi8994-cdp.dtb \
	msm8996-v3.0-pmi8994-mtp.dtb \
	msm8996-v3.0-pmi8994-pm8004-cdp.dtb \
	msm8996-v3.0-pmi8994-pm8004-mtp.dtb \
	msm8996-v3.0-pmi8994-pm8004-pmk8001-cdp.dtb \
	msm8996-v3.0-pmi8994-pmk8001-cdp.dtb \
	msm8996-v3.0-pmi8996-cdp.dtb \
	msm8996-v3.0-pmi8996-mtp.dtb \
	msm8996-v3.0-fluid.dtb \
	msm8996-v3.0-liquid.dtb \
	msm8996-v3.0-dtp.dtb \
	apq8096-v2-pmi8994-mtp.dtb \
	apq8096-v2-liquid.dtb \
	apq8096-v2-dragonboard.dtb \
	apq8096-v2-auto-dragonboard.dtb \
	apq8096-v3-pmi8994-cdp.dtb \
	apq8096-v3-pmi8994-mtp.dtb \
	apq8096-v3-pmi8994-pmk8001-cdp.dtb \
	apq8096-v3-pmi8994-pm8004-cdp.dtb \
	apq8096-v3-pmi8994-pm8004-pmk8001-cdp.dtb \
	apq8096-v3-pmi8996-cdp.dtb \
	apq8096-v3-pmi8996-mtp.dtb \
	apq8096-v3-liquid.dtb \
	apq8096-v3-dragonboard.dtb \
	apq8096-v3-mediabox.dtb \
	apq8096-v3-sbc.dtb \
	apq8096-v3-auto-dragonboard.dtb \
	apq8096-v3-auto-adp.dtb \
	apq8096-v3-auto-cdp.dtb \
	apq8096-v3-drone.dtb \
	apq8096-v3.0-pmi8994-cdp.dtb \
	apq8096-v3.0-pmi8994-mtp.dtb \
	apq8096-v3.0-pmi8994-pm8004-cdp.dtb \
	apq8096-v3.0-pmi8994-pm8004-pmk8001-cdp.dtb \
	apq8096-v3.0-pmi8994-pmk8001-cdp.dtb \
	apq8096-v3.0-pmi8996-cdp.dtb \
	apq8096-v3.0-pmi8996-mtp.dtb \
	apq8096-v3.0-liquid.dtb \
	apq8096-v3.0-dragonboard.dtb \
	apq8096-v3-pmi8994-mdm9x55-i2s-cdp.dtb \
	apq8096-v3-pmi8994-pm8004-mdm9x55-i2s-cdp.dtb \
	apq8096-v3-pmi8994-pm8004-pmk8001-mdm9x55-i2s-cdp.dtb \
	apq8096-v3-pmi8994-pmk8001-mdm9x55-i2s-cdp.dtb \
	apq8096-v3-pmi8996-mdm9x55-i2s-cdp.dtb \
	apq8096-v3-pmi8994-mdm9x55-i2s-mtp.dtb \
	apq8096-v3-pmi8994-mdm9x55-slimbus-mtp.dtb \
	apq8096-v3-pmi8996-mdm9x55-i2s-mtp.dtb \
	apq8096-v3-pmi8996-mdm9x55-slimbus-mtp.dtb \
	apq8096-v3-pmi8996-dragonboard.dtb

dtb-$(CONFIG_ARCH_SDXPOORWILLS) += sdxpoorwills-rumi.dtb \
	sdxpoorwills-cdp.dtb \
	sdxpoorwills-mtp.dtb \
	sdxpoorwills-atp.dtb \
	sdxpoorwills-ttp.dtb \
	sdxpoorwills-cdp-256.dtb \
	sdxpoorwills-mtp-256.dtb \
	sdxpoorwills-dualwifi-cdp.dtb \
	sdxpoorwills-dualwifi-mtp.dtb \
	sdxpoorwills-pcie-ep-cdp-256.dtb \
	sdxpoorwills-pcie-ep-mtp-256.dtb \
	sdxpoorwills-pcie-ep-cdp.dtb \
	sdxpoorwills-pcie-ep-mtp.dtb \
	sdxpoorwills-v2-mtp.dtb \
	sdxpoorwills-v2-cdp.dtb

dtb-$(CONFIG_ARCH_MDM9650) += mdm9650-nand-mtp.dtb \
	mdm9650-ttp.dtb \
	mdm9650-v1.1-nand-mtp.dtb \
	mdm9650-v1.1-nand-cv2x.dtb

dtb-$(CONFIG_ARCH_MDM9607) += mdm9607-mtp.dtb \
	mdm9607-ttp.dtb

targets += dtbs

include $(srctree)/arch/arm64/boot/dts/qcom/Makefile
$(obj)/%.dtb: $(src)/../../../../arm64/boot/dts/qcom/%.dts FORCE
	$(call if_changed_dep,dtc)

ifeq ($(CONFIG_BUILD_ARM64_DT_OVERLAY),y)
$(obj)/%.dtbo:$(src)/../../../../arm64/boot/dts/qcom/%.dts FORCE
	$(call if_changed_dep,dtc)
	$(call if_changed,dtbo_verify)

dtb-$(CONFIG_ARCH_MSM8909) += msm8909-pm8916-mtp.dtb \
	msm8909-cdp.dtb \
        msm8909-1gb-qrd-skuc.dtb \
        msm8909-1gb-qrd-skue.dtb \
        msm8909-qrd-skue.dtb \
	sdw2100-msm8909w-wtp.dtb \
	sdw2100-apq8009w-wtp.dtb \
	apq8009w-cdp.dtb \
	sdw2100-msm8909w-swoctp.dtb \
	msm8909w-swoctp-circpanel.dtb \
	apq8009w-swoctp-circpanel.dtb \
	apq8009w-nowgr-swoctp.dtb \
	sdw2100-apq8009w-nowgr-swoctp-circpanel.dtb \
	msm8909-pm8916-cdp.dtb \
	msm8909w-cdp.dtb \
	sdw2100-msm8909w-1gb-swoctp-circpanel.dtb \
	sdw3100-msm8909w-wtp.dtb \
	sdw2500-msm8909w-wtp.dtb \
	sdw3100-apq8009w-wtp.dtb \
	sdw3100-apq8009w-alpha.dtb \
	sdw2500-apq8009w-wtp.dtb \
	apq8009-mtp-wcd9326.dtb \
	msm8909-mtp-wcd9326.dtb \
	msm8909-mtp-wcd9326-refboard.dtb \
	msm8909-512mb-mtp-wcd9326-refboard.dtb \
	msm8909-512mb-cdp-wcd9326-refboard.dtb \
	msm8909-512mb-rcm-wcd9326-refboard.dtb \
	msm8909-cdp-wcd9326-refboard.dtb \
	msm8909-rcm-wcd9326-refboard.dtb \
	apq8009-mtp-wcd9326-refboard.dtb \
	apq8009-512mb-mtp-wcd9326-refboard.dtb \
	apq8009-512mb-cdp-wcd9326-refboard.dtb \
	apq8009-512mb-rcm-wcd9326-refboard.dtb \
	apq8009-cdp-wcd9326-refboard.dtb \
	apq8009-rcm-wcd9326-refboard.dtb \
	apq8009-robot-refboard.dtb \
	apq8009-robot-som-refboard.dtb \
	apq8009-robot-rome.dtb \
	apq8009-mtp-drone.dtb \
	apq8009-mtp-wcd9326-excelpoint-refboard.dtb \
	msm8909-mtp.dtb \
	msm8909-1gb-mtp.dtb \
	msm8909-1gb-rcm.dtb \
	msm8909-pm8916-1gb-rcm.dtb \
	msm8909-1gb-cdp.dtb \
	apq8009-ext-codec-dragon.dtb \
	apq8009-dragon.dtb
endif

dtbs: $(addprefix $(obj)/,$(dtb-y)) $(addprefix $(obj)/,$(dtbo-y))
else
dtbs: $(addprefix $(obj)/,$(dtb-y))
endif
clean-files := *.dtb
